function Projects() {
  const items = [
    { href: 'https://github.com/alon1406/CityScan', title: 'CityScan', body: 'Map-based platform where residents report urban hazards—potholes, broken streetlights, debris, flooding—on a live shared map.\n\nWhat you can do: search by address or click on the map to pick a spot; sign in to submit reports with type and description; view all hazards as markers; filter by category and status. AI (Gemini) checks for similar issues within 50m and blocks duplicates with a clear message.\n\nOne place for reports, one view for the city. Built with React, Node.js, MongoDB, and a Python + FastAPI AI service.', linkText: 'View on GitHub' },
    { href: 'https://city-scan-tawny.vercel.app/', title: 'CityScan Demo', body: 'Front-end demo — no backend or AI; data is saved in your browser only.\n\nUser: view the map, search by address, click to add a report, choose hazard type and description, see all reports as markers.\n\nAdmin: sign in as admin to see all reports in a list, update status (e.g. open → in progress → fixed), and manage hazards. Use the demo login buttons to try both User and Admin roles.', linkText: 'View Demo' },
    { href: 'https://github.com/alon1406/SmartCollect', title: 'Integrative project: SmartCollect', body: 'Municipal waste collection system — a Spring Boot REST API that keeps bins, trucks and collection routes in one coordinated place.\n\nWhat you can do: sign in as Admin, Operator or Driver, each with its own dashboard; register bins and trucks; plan and assign collection routes; report a collection from the road and have every affected record update together in a single atomic operation; review a full audit trail of who did what.\n\nBuilt on a generic object model, so adding a new entity type needs no schema change. Java, Spring Boot, PostgreSQL and Docker, tested with JUnit 5 and TestContainers.', linkText: 'View on GitHub' },
    { href: 'https://drive.google.com/file/d/1Kae8agvoGMIFb7lWrvZPMkS4zwGVsQFZ/view?usp=sharing', title: 'Game Development course: Mistic Cave', body: 'A first-person adventure built in Unity, played across three connected scenes — a village, a cave and a castle.\n\nThe story: the innkeeper tells you a monster has taken the princess from the castle. To earn the sword you descend into the cave and collect 5 coins and 3 diamonds, which unlocks the chest holding it. Then you climb to the castle, kill the beast, and escort the princess home.\n\nWhat is under it: branching NPC dialogue with real choices, a multi-stage quest chain with objectives and a quest log, melee combat with enemy AI, health and respawn, and collectibles that persist across scenes and sessions. The village, cave and castle are each generated by custom Unity editor tools I wrote. Built in C#.', linkText: 'Watch Video' },
    { href: 'https://todo-app-omega-snowy-46.vercel.app/', title: 'Todo App', body: 'A personal todo app you can use in the browser.\n\nWhat you can do: add new tasks (you cannot set a time or date in the past); search for tasks; mark tasks complete or incomplete; edit task text; delete tasks; see your full list in one place.\n\nTasks that pass their due time without being completed show as overdue.\n\nQuick to use — open the link and start adding tasks.', linkText: 'View Demo' },
    { href: 'https://github.com/alon1406/AcademicEquipmentOrderSystem', title: 'Cyber Security course: Academic Equipment Order System', body: 'Course project focused on secure equipment ordering workflows for academic use, with emphasis on authentication, authorization, and safe data handling.', linkText: 'View on GitHub' },
    { href: 'https://github.com/alon1406/OOP_SQL', title: 'Database course: OOP with SQL', body: 'Extension of the OOP Java project by connecting it to a PostgreSQL database using SQL, developed as part of the Database course.', linkText: 'View on GitHub' },
    { href: 'https://github.com/alon1406/OOP', title: 'OOP course: OOP – Java', body: 'Object-oriented programming project in Java, based on core OOP principles learned in the OOP course.', linkText: 'View on GitHub' },
    { href: 'https://github.com/alon1406/2048-Ubuntu', title: 'C course: 2048 – Ubuntu', body: 'Implementation of the 2048 game in C for Ubuntu as part of the C programming course.', linkText: 'View on GitHub' },
  ]
  return (
    <section className="panel" id="projects" data-reveal>
      <div className="panel__header">
        <p className="eyebrow">Projects</p>
        <h2>Academic & self-learning projects</h2>
      </div>
      <div className="projects-list">
        {items.map((item) => (
          <a key={item.href} className="project-card card" href={item.href} target="_blank" rel="noreferrer noopener">
            <div className="project-main">
              <h3 className="card__title">{item.title}</h3>
              <p className="card__body">{item.body}</p>
            </div>
            <span className="project-link">{item.linkText}</span>
          </a>
        ))}
      </div>
    </section>
  )
}

export default Projects
